# Numpy基礎
配列を用いた演算、行列計算

numyの型 ndarray (N-dimensional array)

多次元配列を扱うためのクラス

In [154]:
 import numpy as np

In [155]:
#配列生成１
a = np.arange(0,9)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [156]:
#配列生成２
b = np.array([1,2,3])
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [157]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [158]:
#転置
print(c.T)
print(c.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [159]:
#要素の数
print(c.size)
print(c.T.size)

6
6


In [160]:
#次元数
a = np.arange(0,9)
c = np.array([[1,2,3],[4,5,6]])
print(a)
print("次元数:",a.ndim)
print(c)
print("次元数:",c.ndim)

[0 1 2 3 4 5 6 7 8]
次元数: 1
[[1 2 3]
 [4 5 6]]
次元数: 2


In [161]:
data1 = np.arange(20,40)
print(data1)
print("要素数")
print(data1.size)
print(len(data1))

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
要素数
20
20


In [162]:
#スライスを用いた抽出
data2 = data1[3:9]
print(data2)
data2

[23 24 25 26 27 28]


array([23, 24, 25, 26, 27, 28])

## 配列計算　行列計算

In [163]:
#合計
data2.sum()

153

In [164]:
#平均
data2.mean()

25.5

In [165]:
#乗算
data2 *3

array([69, 72, 75, 78, 81, 84])

In [166]:
#加算
data2 +100

array([123, 124, 125, 126, 127, 128])

In [167]:
data3 = np.array([2,4,6,8])
data4 = np.array([10,20,30,40])

In [168]:
#加算
data3 + data4

array([12, 24, 36, 48])

In [169]:
#乗算
data3*data4

array([ 20,  80, 180, 320])

## 乱数

In [170]:
#一様乱数
print(np.random.rand())#: 0.0以上、1.0未満 　　　　　　　　　１個
print(np.random.rand(5))#: 0.0以上、1.0未満　　　　　　　　５個

0.08026782767400875
[0.61984178 0.45748138 0.33644268 0.19110826 0.77831816]


In [171]:
#正規分布乱数 平均0、分散1（標準偏差1）
print(np.random.randn())#: 0.0以上、1.0未満 　　　　　　　　　１個
print(np.random.randn(5))#: 0.0以上、1.0未満　　　　　　　　５個

1.260082096573924
[ 0.16749798 -1.28455936  0.29681568  0.08001668  0.05521311]


In [172]:
np.random.randint(0,30,10) #最小値, 最大値, 要素数

array([22,  5,  0, 28, 13, 11, 17,  1, 29, 25])

In [173]:
np.random.randint(0,30,(5,3))

array([[28,  0, 12],
       [19, 26, 26],
       [ 5,  2, 13],
       [ 7, 18, 24],
       [25,  2,  8]])

In [174]:
#乱数のシード
np.random.seed(10)
data5 = np.random.randint(0,9,3)#0から8までの乱数を3個生成してリストへ格納
data5

array([4, 0, 1])

In [175]:
np.random.seed(115)
data6 = np.random.randint(0,9,3)#0から8までの乱数を3個生成してリストへ格納
data6

array([2, 0, 2])

In [176]:
data7= np.random.randint(0,9,3)#0から8までの乱数を3個生成してリストへ格納
data7

array([6, 0, 5])

## その他

In [177]:
array1 = np.array([2, 3, 3, 1, 4, 4, 5, 0, 5, 4]) 
print("最大値:{}".format(array1.max()))
print(f'最小値:{array1.min()}')
print(np.argmax(array1))#最大値のindex
print(np.argmin(array1))#最大値のindex

最大値:5
最小値:0
6
7


## ・APPENDの挙動

●おさらい(listヘのappend,extend ←numpyとは無関係)

In [199]:
#配列に対するAppend
listA = [1,2,3]
listA.append([5,6,7])
listA#listA自体が上書きされる。かつ、[5,6,7]を追加する

[1, 2, 3, [5, 6, 7]]

In [200]:
#配列に対するExtend
listA = [1,2,3]
listA.extend([5,6,7])
listA#listA自体が上書きされる。[5,6,7]は[]が除かれて格納される

[1, 2, 3, 5, 6, 7]

●ndarrayヘのappend

In [201]:
array2 =  [1,2,3]
array2 = np.array(array2)
array2

array([1, 2, 3])

In [202]:
np.append(array2,5)

array([1, 2, 3, 5])

In [203]:
array2#元の配列array2は元のまま

array([1, 2, 3])

In [204]:
np.append(array2,[5,6,7]) #l注意listのextend　と同様の動作

array([1, 2, 3, 5, 6, 7])

In [198]:
array2#元の配列array2は元のまま

array([1, 2, 3])